### ISSUE TITLE
Actually assign product ID 0x1209 / 0x27da on pid.codes?

### ISSUE THREAD

**Issue by sobukus** [seife/marble_fx_digistump#1]
The code seems to use the VID/PID pair 0x1209 / 0x27da, which so far ist not

  https://pid.codes/1209/27da/

registered. Was it attempted yet to register this project with its own ID as „TrackMan Marble FX” (or is it actually more generic for other Logitec PS/2 devices, so it should be „4-button PS/2 TrackMan” or such)?

The process seems not too complicated: https://pid.codes/howto/

I guess anyone could do that, but it makes sense the actual project maintainer/author does it;-)

I'm keen to trying this with two TrackMan devices, probably just as an external converter at firs, and just stumbled over the open question of USB ID in the sources (in search for pinout information, which I will for sure locate somewhere …).

**Comment by seife** [comment]
I didn't and as the digistump version did not work that well long term with windows hosts. I basically abandoned it for the arduino-leonardo version https://github.com/seife/marble_fx here.
I'm not even sure anymore how I came up with the 0x27da, I maybe just copied it over from the DigiSparkMouse usbconfig which probably is just the V-USB id :-)

The ATMega32u4 / Arduino Leonardo version also does the same: it just changes the VID to 1209 but keeps the default leonardo VID of 8036, so that one is 1209:8036 (if compiled with my scripts, it is almost impossible to change the PID if someone compiles it with the Arduino IDE, at least that was the state when I last tried).

As this does not need any special driver on the Host, the PID/VID is almost meaningless, I just changed it so that I could rename it to display a nicer device description without clashing with V-USB stuff.

So no, I will not go pursue the registration, because I consider this project abandoned because it was finally not successfull (I'll state this on the initial README to make this clear).

Pinout is documented in the source file, https://github.com/seife/marble_fx_digistump/blob/5fad8776b0bf1cc058b3e91a75a07e3fe72c9758/marble_fx_digistump.ino#L24

**Comment by sobukus** [comment]
Oh, I see. Can you elaborate on what did not work well with Windows hosts? Something that could be improved or a basic performance issue with the hardware? Since I got those digispark boards now, I'll try to get along with the old code, I presume. The PID/VID does play some role, though. I need to address the USB mouse on my laptop to disable it going to sleep all the time. It seems not to be hard to get one of those IDs reserved and this avoids clashes with any further Arduino-type experiments with USB devices …

**Comment by seife** [comment]
Timing.
The USB timing is very delicate. Also the PS2 polling is time critical. During resume, the USB device was just not recognized at all often, going through a virtual "plug-unplug-plug-unplug..." Cycle, ending in "the usb device you recently plugged was not detected properly". Sometimes physically unplugging the thing and replugging it worked, sometimes it seems the timing calibration data had been so messed up that only a "JTAG" reprogramming of the digispark including the bootloader would make it work again at all.

I tried all sorts of things, including replacing the micronucleus bootloader with a recompiled one without programming functionality (never visible unless you reset the device via the reset button), but it did not make it work reliably.
I'd really just use the digisparks for simple HID devices that do not have to do time-critical protocol translation, like a Joystick or a mouse jiggler.

**Comment by sobukus** [comment]
OK. The first digispark bricked itself during upload (erase error and subsequently not working on USB anymore) and the other managed to take the program, reported itself as TrackMan for a moment, but soon drops out with USB errors. This was on a Thinkpad under Linux.

So my experience and question here served to update the project description and warn others. The proper USB in the 32u4 seems to be a much better bet. Trying that next time. Thanks for your work, in any case!
